/**
 * Tutorial Steps Configuration
 * IQC Compliant: User onboarding with step-by-step guidance
 */

import type { TutorialStep } from '../components/ui/Tutorial';

export const KINGDOM_DASHBOARD_TUTORIAL: TutorialStep[] = [
  {
    id: 'welcome',
    title: '👑 Welcome to Your Kingdom!',
    description: 'This is your kingdom dashboard - your command center for managing resources, territories, and military operations. Let\'s take a quick tour!',
    position: 'bottom'
  },
  {
    id: 'resources',
    title: '💰 Resources Overview',
    description: 'These are your core resources: Gold (economy), Population (workforce), Land (territory), and Turns (actions). You need turns to perform most actions in the game.',
    targetElement: '.resources-panel',
    position: 'bottom'
  },
  {
    id: 'generate-turns',
    title: '⏱️ Generate Turns',
    description: 'Turns regenerate every 20 minutes (3 per hour). Click "Generate Turns" to get more turns for actions. You can also encamp for bonus turns!',
    targetElement: '.resource-actions',
    position: 'top'
  },
  {
    id: 'race-abilities',
    title: '✨ Race Abilities',
    description: 'Your race provides unique bonuses and special abilities. Each race excels in different areas - economy, combat, magic, or espionage.',
    targetElement: '.race-stats-panel',
    position: 'bottom'
  },
  {
    id: 'territories',
    title: '🏰 Territories',
    description: 'Territories generate resources and provide strategic advantages. Expand your kingdom by claiming new territories and upgrading existing ones.',
    targetElement: '.territories-panel',
    position: 'top'
  },
  {
    id: 'combat',
    title: '⚔️ Combat Operations',
    description: 'Attack other kingdoms to gain land and resources. Build armies, create formations, and execute strategic battles.',
    targetElement: 'button[class*="action-btn"]:has(img[alt="Combat"])',
    position: 'left'
  },
  {
    id: 'magic',
    title: '🔮 Magic System',
    description: 'Cast powerful spells to damage enemies, remove shields, or boost your kingdom. Build temples to increase your magical power!',
    targetElement: 'button[class*="action-btn"]:has(img[alt="Magic"])',
    position: 'left'
  },
  {
    id: 'alliances',
    title: '🤝 Alliances',
    description: 'Join or create alliances to coordinate with other players. Share intelligence, plan attacks, and defend each other.',
    targetElement: 'button[class*="action-btn"]:has(img[alt="Alliance"])',
    position: 'left'
  },
  {
    id: 'world-map',
    title: '🗺️ World Map',
    description: 'View the interactive world map to see all territories, plan expansions, and identify strategic targets.',
    targetElement: 'button[class*="action-btn"]:has(img[alt="World Map"])',
    position: 'left'
  },
  {
    id: 'complete',
    title: '🎉 Ready to Rule!',
    description: 'You\'re all set! Start by generating turns, claiming territories, and building your army. Good luck, ruler!',
    position: 'bottom'
  }
];

export const COMBAT_TUTORIAL: TutorialStep[] = [
  {
    id: 'combat-intro',
    title: '⚔️ Combat System',
    description: 'Welcome to the combat interface! Here you can build armies, create formations, and attack other kingdoms.',
    position: 'bottom'
  },
  {
    id: 'units',
    title: '🛡️ Available Units',
    description: 'These are your available units. Each unit type has different offense and defense values. Drag to reorder them in your formation.',
    targetElement: '.available-units',
    position: 'right'
  },
  {
    id: 'formations',
    title: '📋 Battle Formations',
    description: 'Create and save formations for different battle scenarios. Formations determine unit order and provide tactical bonuses.',
    targetElement: '.formation-builder',
    position: 'left'
  },
  {
    id: 'attack',
    title: '🎯 Execute Attack',
    description: 'Select your target, choose your formation, and execute the attack. Land gained depends on your offense vs their defense.',
    targetElement: '.battle-execution',
    position: 'top'
  }
];

export const SPELL_CASTING_TUTORIAL: TutorialStep[] = [
  {
    id: 'magic-intro',
    title: '🔮 Magic System',
    description: 'Cast powerful spells to damage enemies or boost your kingdom. Spells require mana and elan.',
    position: 'bottom'
  },
  {
    id: 'mana',
    title: '💙 Mana & Elan',
    description: 'Mana is your magical energy, generated by temples. Elan is earned by casting spells and determines spell tier access.',
    targetElement: '.mana-section',
    position: 'bottom'
  },
  {
    id: 'spell-tiers',
    title: '✨ Spell Tiers',
    description: 'Spells are organized by tier (1-4). Higher tiers require more temples (2%, 4%, 8%, 12%) and deal more damage.',
    targetElement: '.spell-grid',
    position: 'top'
  },
  {
    id: 'casting',
    title: '⚡ Cast Spells',
    description: 'Click a spell to cast it. Some spells require selecting a target. Watch for cooldowns between casts!',
    position: 'bottom'
  }
];

export const TERRITORY_TUTORIAL: TutorialStep[] = [
  {
    id: 'territory-intro',
    title: '🏰 Territory Management',
    description: 'Expand your kingdom by claiming and upgrading territories. Each territory generates resources.',
    position: 'bottom'
  },
  {
    id: 'claim',
    title: '🎯 Claim Territory',
    description: 'Click "Claim Territory" to expand your kingdom. New territories cost gold and turns but provide ongoing income.',
    targetElement: '.territory-item button',
    position: 'top'
  },
  {
    id: 'upgrade',
    title: '⬆️ Upgrade Territory',
    description: 'Upgrade territories to increase resource generation. Higher levels provide better returns on investment.',
    position: 'bottom'
  }
];

export const ALLIANCE_TUTORIAL: TutorialStep[] = [
  {
    id: 'alliance-intro',
    title: '🤝 Alliance System',
    description: 'Alliances provide mutual defense, shared intelligence, and coordinated warfare capabilities.',
    position: 'bottom'
  },
  {
    id: 'browse',
    title: '🔍 Browse Alliances',
    description: 'Browse public alliances to find one that matches your playstyle. Check their power level and member count.',
    targetElement: 'button:has-text("Browse Alliances")',
    position: 'bottom'
  },
  {
    id: 'chat',
    title: '💬 Alliance Chat',
    description: 'Once you join, use the real-time chat to coordinate with allies, share intelligence, and plan attacks.',
    position: 'bottom'
  }
];
